### ISSUE TITLE
CI 설정

### ISSUE THREAD

**Issue by Hm-source** [FiT-8-plus-1-BiT/backend#13]
### 현재 상황
- CI/CD 파이프라인 구축을 진행
   - 우선 GitHub Actions에서 Pull Request(PR), push 시 Spring Boot 빌드만 수행하도록 설정합니다.

### 목표
- 코드 품질 보장.
- 예상치 못한 버그가 배포되는 것 방지.

## 작업 내용
- [x] PR 생성, push 시 자동으로 빌드 실행 
```
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
```
- [x] Spring Boot 프로젝트 빌드 -> 테스트 무조건 모두 통과해야 함.
---
- [x] yml 설정을 서브모듈로 관리하는 것 추가 필요.
    - [x] github PAT 생성 후 organization github secret key 등록
    - [해결]
    ```
    - GitHub → Settings → Developer settings → Personal access tokens (classic)
    - GitHub PAT 생성 페이지(https://github.com/settings/tokens) 로 이동해서 토큰 생성.(생성 후 복사 필수)
    - GitHub Organization 페이지로 이동 [GitHub Organization Settings](https://github.com/settings/organizations)
    - Settings → Secrets and variables → Actions 클릭
    - "New organization secret" 버튼 클릭
    - Name: SUB_MODULE_TOKEN (원하는 이름으로 설정 가능)
    - Value: 방금 생성한 Personal Access Token (PAT) 입력
    - Repository Access 설정
    ```
   - 레포지토리 가져올 때, 서브 모듈도 같이 가져오도록 설정.
   - 서브모듈이 프라이빗이기 때문에, secrets.SUB_MODULE_TOKEN을 사용해서 인증 진행.
    ```
          - name: Checkout Repository
             uses: actions/checkout@v4
             with:
                submodules: true
                token: ${{ secrets.SUB_MODULE_TOKEN }}

          - name: Update Git Submodules
             run: git submodule update --init --recursive
    ```

    - [x] be_sub_module_yml 레파지토리에 있는 yml 파일 가져오도록 build.gradle에 추가해야함.
    ```
    tasks.register("copyPrivate", Copy) {
       from("$projectDir/be_sub_module_yml")  // 서브모듈 경로
       include("*.yml")                    // 복사할 파일 패턴 (*.yml)
       into("$projectDir/src/main/resources")  // 복사 대상 경로
    }

    tasks.named("processResources") {
       dependsOn("copyPrivate")
    }
   tasks.named("build") {
       dependsOn("copyPrivate")
   }
    ```
    
---
 - [x] KMS(kurento media server)가 실행되지 않아서 에러가 발생함.(해당 내용 도커로 실행되도록 workflows에 추가 필요.)
```
Caused by: org.kurento.commons.exception.KurentoException at KurentoClient.java:267
Caused by: org.kurento.jsonrpc.JsonRpcException at AbstractJsonRpcClientWebSocket.java:737
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException
Caused by: java.net.ConnectException at Net.java:-2
```
[해결]
```
      - name: Start Kurento Media Server
        run: |
          docker run -d --name kurento-server -p 8888:8888 kurento/kurento-media-server
          sleep 10
```
---
 - [x] mysql 추가
 - [x] redis 추가
